# Generated by Django 5.0.2 on 2024-03-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYBLOG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_change_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=10)),
                ('mail_of_user', models.EmailField(max_length=254)),
            ],
        ),
    ]
