# Generated by Django 5.0.2 on 2024-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYBLOG', '0003_alter_password_change_request_mail_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_change_request',
            name='user_key',
            field=models.CharField(max_length=50),
        ),
    ]
