# Generated by Django 5.0.2 on 2024-03-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYBLOG', '0004_alter_password_change_request_user_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password_change_request',
            old_name='user_key',
            new_name='user_random_key',
        ),
    ]
